#开发配置
server:
  port: 12345
  servlet:
    session:
      timeout: 1d
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: backend
  data:
    redis:
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器端口,默认为6379.若有改动按改动后的来
      port: 6379
      #Redis服务器连接密码，默认为空，若有设置按设置的来
      password:
      # Redis 默认数据库设置
      database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123456
    url: jdbc:mysql://localhost:3306/errs?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  #  配置时间
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Shanghai
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: cyke0315@163.com
    password: YYf493Ag2DVktyRD
    protocol: smtp
  web:
    cors:
      origin: '*'
      credentials: true
      methods: '*'


# 映射器（Mapper）配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 日志
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.mybatis: DEBUG



